name: ExtDN M2 Coding Standard
on:
  push:
    branches:
      - master

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: build/logs/clover.xml