name: ExtDN M2 Coding Standard
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shell commands
        run: |
          echo "Current directory:"
          pwd
          echo "List files:"
          ls -la
      - uses: extdn/github-actions-m2/magento-coding-standard/8.1@master