name: ExtDN Actions
on: [push]
jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-unit-tests/8.1@master
        env:
          MAGENTO_VERSION: '2.4.5'
          MODULE_NAME: Crealoz_EasyAudit
          COMPOSER_NAME: crealoz/easy-audit-free
          PHPUNIT_FILE: 'phpunit.xml'